# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f6135589eb652db0a6f9adb0baefc759fb75540ec3ed0accb62e9f081dc3b9da937f620c0acbc9e22e96c707e2b7cd150a93aa1f93fc9b7f64de0245c3b03dbf

test:
  secret_key_base: e8156d4404226714457c369fbf508dfef3ec6bb499247b6e2c1939ffe7ec25773095519416edde8e4fa4fb055c71ae63fb0b30907fc31cbe9c521d2237b6c17d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
